### Lists of lists

In [230]:
m=[[1,2,3],[4,5],[6,7,8,9]]
print(m)
print(m[0][:2])

[[1, 2, 3], [4, 5], [6, 7, 8, 9]]
[1, 2]


In [235]:
blocked=[[False,True,True],[False,False,True],[True,False,False]]
def maze(M):
    n=len(M)      ## number of rows
    m=len(M[0])   ## numbers of columns
    R=[[False for i in range(m)] for j in range(n)] #initially all cells are unreachable
    R[0][0]=not M[0][0] # upper left corner is reachable iff it is open
    for i in range(n):  # start from the top row and go down
        for j in range(m): # start from the left column and go right
            if R[i][j]:
                if  i<n-1 and not M[i+1][j]:
                    R[i+1][j]=True
                if j<m-1 and not M[i][j+1]:
                    R[i][j+1]=True
    return R

R=maze(blocked)
print(R)
    

[[True, False, False], [True, True, False], [False, True, True]]


### Lists vs Arrays

- A list is an ordered sequence of objects, similar to arrays
- Operations on lists, however, have **different** meaning than on arrays

In [219]:
a=[1,2,3,4]
print(a*2)


[1, 2, 3, 4, 1, 2, 3, 4]


In [220]:
print(a+1)

TypeError: can only concatenate list (not "int") to list

#### Arrays
- The Python package numpy is the most used package for numerical computation
- We can use arrays (among others) using numpy
- As one can see below, the same operations on lists and arrays have different meaning

In [221]:
import numpy as np
v=np.array([1,2,3,4])
print(v*2) # multiple each element of the array by 2
print(v+1) # add 1 to every element of the array
print(v*v) # multiple each element of the array with itself
print(v.dot(v))


[2 4 6 8]
[2 3 4 5]
[ 1  4  9 16]
30


- Unlike lists, elements of an array **must** have the same type, up to casting

In [177]:
u=np.array(['a',2])
v=np.array([2.2,'a'])
w=np.array([2,2.2])
print(u)
print(v)
print(w)
print(type(u[0]),type(v[0]),type(w[0]))

['a' '2']
['2.2' 'a']
[2.  2.2]
<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.float64'>


#### Slicing as usual
- numpy arrays support slicing, the same way lists do

In [179]:
print(v)
print(v[0:1])

['2.2' 'a']
['2.2']


### Lists of lists vs Matrices

- We have seen before that the elements of a list can be any objects
- In particular each element can be a list itself
- Note that each "inner" list can have different type of elements and different sizes

In [180]:
listOfLists=[['a','b','c'],[4,5,6,7]]
print(listOfLists[0][2])
listOfLists[0][0:2]


c


['a', 'b']

#### Matrices (numpy)
- The numpy package (numerical Python) we use array, a d-dimensional object
- list of lists and 2-d arrays might superficially look the same but they are not
- All elements must have the same type, up to casting
- For array "inner" arrays must have the same length
- **NOTE** if we use _matrix_ instead of _array_ hey could have different sizes.
- You are **DISCOURAGED** from using _matrix_

[[1 2]
 [3 4]]


In [249]:
# 2-d array
m=np.array([[1,2],[3,4]])
print(m)
print("---------")
# 3-d array
n=np.array([[11,12],[13,14]])
print(n)
print("--------")
p=np.array([m,n])
print(p)

p.shape
print("---------")
print(p[0])


[[1 2]
 [3 4]]
---------
[[11 12]
 [13 14]]
--------
[[[ 1  2]
  [ 3  4]]

 [[11 12]
  [13 14]]]
---------
[[1 2]
 [3 4]]


#### Elements with different sizes

- It is possible to have different sizes for the "inner" arrays
- In that case numpy regards them as objects

In [262]:
n=np.array([1,2])
m=np.array([3,4])
# p is a 3-d array
p=np.array([m,n])
print(p,p.shape)
q=np.array([[3,2,1],['a',5],[1,2,3]],dtype=object)
print(q,q.shape)

[[3 4]
 [1 2]] (2, 2)
[list([3, 2, 1]) list(['a', 5]) list([1, 2, 3])] (3,)


### Indexing is different

In [8]:
import numpy as np
ll=[[1,2,3],[4,5,6],[7,8,9]]
m=np.array(ll)
print(m)
ll[0:2][0]
print(m[0:1])
# m[0:1][1] will cause an error
print(m[0:1,1])
m[0,1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[2]


2

In [269]:
v=np.array([1,2,3])
np.dot(p,v)

array([14, 32, 50])

In [270]:
m=np.matrix([[1,0,0],[0,2,2],[0,2,3]])
n=np.linalg.inv(m)
print(n)
print(m.dot(n))
n=m.T
e=np.all(np.equal(m,n))
e

[[ 1.   0.   0. ]
 [ 0.   1.5 -1. ]
 [ 0.  -1.   1. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


True

## Solving a system of equations

- Example:  $$\begin{align*} a_{11}x_1 +\ldots+a_{1n}x_n&=c_1\\ \ldots \ldots \\a_{n1}x_1+\ldots a_{nn}x_n&=c_n\end{align*}$$
- Can be written as 
$$ AX=C$$
- With solution
$$ X=A^{-1}C$$

- Example
$$\begin{align*} x_1+2x_2=3\\3x_1+4x_2=6\end{align*}$$
- Which can be written as
$$\left(\begin{array}{cc}1 &2 \\ 3 & 4\end{array}\right)\left(\begin{array}{c}x_1\\x_2\end{array}\right)=\left(\begin{array}{c}3\\6\end{array}\right)$$
-Therefore

$$\left(\begin{array}{c}x_1\\x_2\end{array}\right)=\left(\begin{array}{cc}1 &2 \\ 3 & 4\end{array}\right)^{-1}\left(\begin{array}{c}3\\6\end{array}\right)$$

In [96]:
m=np.array([[1,2],[3,4]])
c=np.array([[3],[6]])
r=None
if np.linalg.det(m)==0:
    print("No unique solution")
else:
    inv=np.linalg.inv(m)
    r=inv.dot(c)
print(inv)
print(r)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-4.4408921e-16]
 [ 1.5000000e+00]]


### Dictionaries

- Dictionaries are a data structure that stores key/value pairs
- Any situation that requires fast lookup/add/insert the best option is a dictionary

#### Creation

In [45]:
d={'k1':1,'k2':2,'k3':3}

In [39]:
## dict comprehension, need zip to create pairs
months=['January','February','March','April','May','June','July','August','September','October','November','December']
days=[31,28,31,30,31,30,31,31,30,31,30,31]
days_in_month={s:g for s,g in zip(months,days)}

#### lookup/Search

In [40]:
days_in_month['March']

31

In [44]:
days_in_month['Maktag']

KeyError: 'Maktag'

In [43]:
### Safer version
val=days_in_month.get('March')
print(val)
val=days_in_month.get('Maktag')
print(val)

31
None


#### Checking the existence/no value is needed

In [47]:
print('March' in days_in_month)
print('Maktag' in days_in_month)

True
False


#### Adding/updating values

In [55]:
d={}
d['Key1']=1
d['Key2']=2
d['Key3']=3
d['Key2']="Changed" # replaces the old value
d

{'Key1': 1, 'Key2': 'Changed', 'Key3': 3}

### Iterating over keys/values/both

In [ ]:
dx={"a":3,"b":5}
for i in dx.items():
    print(i)
print("---------------")
for k in dx.keys():
    print(k)
print("---------------")
for v in dx.values():
    print(v)


### Removing elements

In [51]:
dx={"a":3,"b":5}
r=dx.pop('a')
print(r)
print(dx)

3
{'b': 5}


#### Adding elements in bulk

In [69]:
dx={"a":3,"b":5}
dx.update({"c":10,"d":20})
dx

{'a': 3, 'b': 5, 'c': 10, 'd': 20}

#### Values can be any object, keys must be immutable

In [73]:
d={"record1":{"January":1,"February":2},"record2":18}
d["record1"]["January"]

1

### Two sum

In [14]:
from random import randint
a=[randint(1,50) for i in range(20)]
print(a)
x=16
d={k:v for v,k in enumerate(a)}
print(d)
for i,u in enumerate(a):
    j=d.get(x-u)
    if j!=None and i!=j:
        print(i,j)

[3, 5, 24, 31, 41, 38, 9, 44, 11, 30, 37, 31, 49, 6, 11, 38, 7, 2, 35, 24]
{3: 0, 5: 1, 24: 19, 31: 11, 41: 4, 38: 15, 9: 6, 44: 7, 11: 14, 30: 9, 37: 10, 49: 12, 6: 13, 7: 16, 2: 17, 35: 18}
1 14
6 16
8 1
14 1
16 6


### Word count
- Given a string _s_ return a dictionary that has the count of each character
- Example: s="abccabc" return d={'a':2,'b':2,'c':3}

In [32]:
x="abbabbab"
dx={}
for c in x:
    if dx.get(c)==None:
        dx[c]=1
    else:
        dx[c]+=1

print(dx)

{'a': 3, 'b': 5}


#### Longest non repeating substring

In [66]:
def lsnrc(s):
    i,max,n=0,0,len(s)
    start,end=0,0
    while i<n:
        d={}
        j=i
        while j<n and s[j] not in d:
            d[s[j]]=j
            j+=1
        if j-i>max:
            start,end,max=i,j,j-i
        if j==n:
            break
        i=d[s[j]]+1
    return max,start,end

s="abcdefauvwcbuvw"
length,start,end=lsnrc(s)
s[start:end]

'bcdefauvw'

#### More efficient version

In [82]:
def lengthOfLongestSubstring(s):
        last_seen = {}
        max_len = 0
 
        start = 0
        for i in range(0, len(s)):
             if s[i] in last_seen:
                 start = max(start, last_seen[s[i]] + 1)
                 
             max_len = max(max_len, i-start + 1)
             last_seen[s[i]] = i
 
        return max_len
s="abcdefbauvwxt"
length,start,end=lsnrc(s)
s[start:end]

'cdefbauvwxt'

## Stacks


- Operations: **push** on top of the stack, and **pop** top of the stack
- Simulate using a list: append and pop


In [91]:
def print_stack(s):
    for e in s[-1::-1]:
        print(e)
    print("-----------")    
stack=[]
stack.append(1)
stack.append(2)
stack.append(3)
print_stack(stack)
stack.pop()
print_stack(stack)


3
2
1
-----------
2
1
-----------


### balanced parentheses


In [83]:
s="(()[])"
stack=[]
for c in s:
    if c==")":
        if len(stack)!=0 and stack[-1]=="(":
            stack.pop()
        else:
            stack.append(c)
    elif c=="]":
        if len(stack)!=0 and stack[-1]=="[":
            stack.pop()
        else:
            stack.append(c)
    else:
        stack.append(c)
print(len(stack)==0)
    

True


### Postfix Calculator

In [56]:
command="3 1 2 + *"  # mult(3,add(1,2)), 3*(1+2)
ops=command.split()
stack=[]
for op in ops:
    if op=='+':
        a,b=stack.pop(),stack.pop()
        stack.append(a+b)
        
    elif op=='*':
        a,b=stack.pop(),stack.pop()
        stack.append(a*b)
    else:
        stack.append(int(op))
print(stack.pop())

9


### Queues
- Also know as First in First out (FIFO ) queue
- Used to implement first come first served strategy
- We implement it using lists
    - enqueue--> append to the end of the list
    - dequeue --> remove from the beginning

In [1]:
def enqueue(Q,val):
    Q.append(val)
def dequeue(Q):
    val=Q.pop(0)
    return val
def empty(Q):
    return len(Q)==0

input_as_string="18 3 17 2 22 25 45 89 6"
arrivals=[int(x) for x in input_as_string.split()]
Q=[]
for v in arrivals:
    enqueue(Q,v)


In [12]:
## Process items first come first served
while not empty(Q):
    val=dequeue(Q)
    print(f"Processing {val}")

Processing 18
Processing 3
Processing 17
Processing 2
Processing 22
Processing 25
Processing 45
Processing 89
Processing 6


### Breadth first search

![bfs](bfs-small.png)

In [3]:
adj=[[1,2,6],[0,3],[0,4],[1,7],[2],[7],[0,7,8],[3,5,6],[6]]
marked=9*[False]
q=[0]
marked[0]=True
d=0
while not empty(q):
    node=dequeue(q)
    print(f"processing node {node} at distance {d}")
    d+=1
    for n in adj[node]:
        if not marked[n]:
            enqueue(q,n)
            marked[n]=True
            
        

processing node 0 at distance 0
processing node 1 at distance 1
processing node 2 at distance 2
processing node 6 at distance 3
processing node 3 at distance 4
processing node 4 at distance 5
processing node 7 at distance 6
processing node 8 at distance 7
processing node 5 at distance 8
