### Lists of lists

In [230]:
m=[[1,2,3],[4,5],[6,7,8,9]]
print(m)
print(m[0][:2])

[[1, 2, 3], [4, 5], [6, 7, 8, 9]]
[1, 2]


In [235]:
blocked=[[False,True,True],[False,False,True],[True,False,False]]
def maze(M):
    n=len(M)      ## number of rows
    m=len(M[0])   ## numbers of columns
    R=[[False for i in range(m)] for j in range(n)] #initially all cells are unreachable
    R[0][0]=not M[0][0] # upper left corner is reachable iff it is open
    for i in range(n):  # start from the top row and go down
        for j in range(m): # start from the left column and go right
            if R[i][j]:
                if  i<n-1 and not M[i+1][j]:
                    R[i+1][j]=True
                if j<m-1 and not M[i][j+1]:
                    R[i][j+1]=True
    return R

R=maze(blocked)
print(R)
    

[[True, False, False], [True, True, False], [False, True, True]]


### Lists vs Arrays

- A list is an ordered sequence of objects, similar to arrays
- Operations on lists, however, have **different** meaning than on arrays

In [219]:
a=[1,2,3,4]
print(a*2)


[1, 2, 3, 4, 1, 2, 3, 4]


In [220]:
print(a+1)

TypeError: can only concatenate list (not "int") to list

#### Arrays
- The Python package numpy is the most used package for numerical computation
- We can use arrays (among others) using numpy
- As one can see below, the same operations on lists and arrays have different meaning

In [221]:
import numpy as np
v=np.array([1,2,3,4])
print(v*2) # multiple each element of the array by 2
print(v+1) # add 1 to every element of the array
print(v*v) # multiple each element of the array with itself
print(v.dot(v))


[2 4 6 8]
[2 3 4 5]
[ 1  4  9 16]
30


- Unlike lists, elements of an array **must** have the same type, up to casting

In [177]:
u=np.array(['a',2])
v=np.array([2.2,'a'])
w=np.array([2,2.2])
print(u)
print(v)
print(w)
print(type(u[0]),type(v[0]),type(w[0]))

['a' '2']
['2.2' 'a']
[2.  2.2]
<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.float64'>


#### Slicing as usual
- numpy arrays support slicing, the same way lists do

In [179]:
print(v)
print(v[0:1])

['2.2' 'a']
['2.2']


### Lists of lists vs Matrices

- We have seen before that the elements of a list can be any objects
- In particular each element can be a list itself
- Note that each "inner" list can have different type of elements and different sizes

In [180]:
listOfLists=[['a','b','c'],[4,5,6,7]]
print(listOfLists[0][2])
listOfLists[0][0:2]


c


['a', 'b']

#### Matrices (numpy)
- The numpy package (numerical Python) we use array, a d-dimensional object
- list of lists and 2-d arrays might superficially look the same but they are not
- All elements must have the same type, up to casting
- For array "inner" arrays must have the same length
- **NOTE** if we use _matrix_ instead of _array_ hey could have different sizes.
- You are **DISCOURAGED** from using _matrix_

[[1 2]
 [3 4]]


In [249]:
# 2-d array
m=np.array([[1,2],[3,4]])
print(m)
print("---------")
# 3-d array
n=np.array([[11,12],[13,14]])
print(n)
print("--------")
p=np.array([m,n])
print(p)

p.shape
print("---------")
print(p[0])


[[1 2]
 [3 4]]
---------
[[11 12]
 [13 14]]
--------
[[[ 1  2]
  [ 3  4]]

 [[11 12]
  [13 14]]]
---------
[[1 2]
 [3 4]]


#### Elements with different sizes

- It is possible to have different sizes for the "inner" arrays
- In that case numpy regards them as objects

In [262]:
n=np.array([1,2])
m=np.array([3,4])
# p is a 3-d array
p=np.array([m,n])
print(p,p.shape)
q=np.array([[3,2,1],['a',5],[1,2,3]],dtype=object)
print(q,q.shape)

[[3 4]
 [1 2]] (2, 2)
[list([3, 2, 1]) list(['a', 5]) list([1, 2, 3])] (3,)


In [269]:
v=np.array([1,2,3])
np.dot(p,v)

array([14, 32, 50])

In [270]:
m=np.matrix([[1,0,0],[0,2,2],[0,2,3]])
n=np.linalg.inv(m)
print(n)
print(m.dot(n))
n=m.T
e=np.all(np.equal(m,n))
e

[[ 1.   0.   0. ]
 [ 0.   1.5 -1. ]
 [ 0.  -1.   1. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


True

## Solving a system of equations

- Example:  $$\begin{align*} a_{11}x_1 +\ldots+a_{1n}x_n&=c_1\\ \ldots \ldots \\a_{n1}x_1+\ldots a_{nn}x_n&=c_n\end{align*}$$
- Can be written as 
$$ AX=C$$
- With solution
$$ X=A^{-1}C$$

- Example
$$\begin{align*} x_1+2x_2=3\\3x_1+4x_2=6\end{align*}$$
- Which can be written as
$$\left(\begin{array}{cc}1 &2 \\ 3 & 4\end{array}\right)\left(\begin{array}{c}x_1\\x_2\end{array}\right)=\left(\begin{array}{c}3\\6\end{array}\right)$$
-Therefore

$$\left(\begin{array}{c}x_1\\x_2\end{array}\right)=\left(\begin{array}{cc}1 &2 \\ 3 & 4\end{array}\right)^{-1}\left(\begin{array}{c}3\\6\end{array}\right)$$

In [96]:
m=np.array([[1,2],[3,4]])
c=np.array([[3],[6]])
r=None
if np.linalg.det(m)==0:
    print("No unique solution")
else:
    inv=np.linalg.inv(m)
    r=inv.dot(c)
print(inv)
print(r)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-4.4408921e-16]
 [ 1.5000000e+00]]


### Dictionaries

In [191]:
d={'k1':1,'k2':2,'k3':3}
d['k4']

KeyError: 'k4'

In [85]:
students=['ali','joe']
grades=[100,99]
roster={s:g for s,g in zip(students,grades)}
print(roster)

{'ali': 100, 'joe': 99}


### Queues
- Also know as First in First out (FIFO ) queue
- Used to implement first come first served strategy

In [58]:
x=[2**i for i in range(10)]
x

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [66]:
x=[i for i in range(100000000)]


In [73]:
x.pop(1000)

1005

In [68]:
x.pop()

99999999

## Stacks



### balanced parentheses


In [83]:
s="(()[])"
stack=[]
for c in s:
    if c==")":
        if len(stack)!=0 and stack[-1]=="(":
            stack.pop()
        else:
            stack.append(c)
    elif c=="]":
        if len(stack)!=0 and stack[-1]=="[":
            stack.pop()
        else:
            stack.append(c)
    else:
        stack.append(c)
print(len(stack)==0)
    

True


### Postfix Calculator

In [56]:
command="3 1 2 + *"  # mult(3,add(1,2)), 3*(1+2)
ops=command.split()
stack=[]
for op in ops:
    if op=='+':
        a,b=stack.pop(),stack.pop()
        stack.append(a+b)
        
    elif op=='*':
        a,b=stack.pop(),stack.pop()
        stack.append(a*b)
    else:
        stack.append(int(op))
print(stack.pop())

9
